### ISSUE TITLE
missing MODULE

### ISSUE THREAD

**Issue by boxmaninnit** [ThatBadName/Closed-Construction-OpenSource#6]
[antiCrash] :: Unhandled Rejection/Catch
Error: Cannot find module '../../things/lootBoxes/boxes'
Require stack:
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\events\client\interactionCreate.js
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\functions\handlers\handleEvents.js
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\events\client\interactionCreate.js:15:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\events\\client\\interactionCreate.js',
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\functions\\handlers\\handleEvents.js',
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\bot.js'
  ]
} Promise {
  <rejected> Error: Cannot find module '../../things/lootBoxes/boxes'
  Require stack:
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\events\client\interactionCreate.js
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\functions\handlers\handleEvents.js
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\bot.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\events\client\interactionCreate.js:15:15)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\events\\client\\interactionCreate.js',
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\functions\\handlers\\handleEvents.js',
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\bot.js'
    ]
  }
}
 [antiCrash] :: Unhandled Rejection/Catch
Error: Cannot find module '../../commandFunctions'
Require stack:
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\globalCommands\Economy\game.js
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\functions\handlers\handleGlobalCommands.js
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\globalCommands\Economy\game.js:9:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\globalCommands\\Economy\\game.js',
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\functions\\handlers\\handleGlobalCommands.js',
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\bot.js'
  ]
} Promise {
  <rejected> Error: Cannot find module '../../commandFunctions'
  Require stack:
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\globalCommands\Economy\game.js
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\functions\handlers\handleGlobalCommands.js
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\bot.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\globalCommands\Economy\game.js:9:19)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\globalCommands\\Economy\\game.js',
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\functions\\handlers\\handleGlobalCommands.js',
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\bot.js'
    ]
  }
}
 [antiCrash] :: Unhandled Rejection/Catch
Error: Cannot find module '../../commandFunctions'
Require stack:
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\localCommands\BotModeration\blacklist.js
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\functions\handlers\handleLocalCommands.js
- C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\localCommands\BotModeration\blacklist.js:11:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\localCommands\\BotModeration\\blacklist.js',
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\functions\\handlers\\handleLocalCommands.js',
    'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\bot.js'
  ]
} Promise {
  <rejected> Error: Cannot find module '../../commandFunctions'
  Require stack:
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\localCommands\BotModeration\blacklist.js
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\functions\handlers\handleLocalCommands.js
  - C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\bot.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (C:\Users\******\Documents\GitHub\Closed-Construction-OpenSource\src\localCommands\BotModeration\blacklist.js:11:19)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\localCommands\\BotModeration\\blacklist.js',
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\functions\\handlers\\handleLocalCommands.js',
      'C:\\Users\\******\\Documents\\GitHub\\Closed-Construction-OpenSource\\src\\bot.js'
    ]
  }
}

**Comment by boxmaninnit** [comment]
should be fixed in a pull request by me later, or later on saturday.
